# Generated by Django 2.2.10 on 2021-08-06 17:45

from django.db import migrations, models
import django.db.models.deletion
import manage_menu.storage
import manage_menu.storage_banner
import manage_menu.storage_shop_photo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customized',
            fields=[
                ('customized_id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_price', models.IntegerField()),
                ('add_other', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customized',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_quantity', models.IntegerField()),
                ('detail_price', models.IntegerField()),
            ],
            options={
                'db_table': 'order_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAddrule',
            fields=[
                ('product_add', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('add_chinese', models.CharField(blank=True, max_length=50, null=True)),
                ('add_table', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'product_addrule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCase',
            fields=[
                ('product_add', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plus_id', models.IntegerField()),
            ],
            options={
                'db_table': 'product_case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('productsize_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_size', models.CharField(max_length=10)),
                ('product_price', models.IntegerField()),
            ],
            options={
                'db_table': 'product_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Singleplus1',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'singleplus_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Singleplus2',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'singleplus_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Singleplus3',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'singleplus_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('sort_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_type', models.CharField(max_length=10)),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'sort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('stuff_account', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stuff_password', models.CharField(max_length=10)),
                ('stuff_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stuff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(storage=manage_menu.storage_banner.OverwriteStorage_banner(), upload_to='')),
                ('URL', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'advertise',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_account', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('guest_password', models.CharField(max_length=10)),
                ('guest_name', models.CharField(max_length=10)),
                ('guest_phone', models.CharField(max_length=12)),
                ('guest_address', models.CharField(max_length=50)),
                ('guest_mail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='Multipleplus',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'multipleplus',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_sort', models.CharField(max_length=10)),
                ('product_pic', models.ImageField(storage=manage_menu.storage.OverwriteStorage(), upload_to='')),
                ('product_add', models.CharField(max_length=10)),
                ('product_introduction', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('shop_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_phone', models.CharField(max_length=10)),
                ('shop_admin', models.CharField(max_length=50)),
                ('photo', models.ImageField(storage=manage_menu.storage_shop_photo.OverwriteStorage_shop_photo(), upload_to='')),
            ],
            options={
                'db_table': 'shop_detail',
            },
        ),
        migrations.CreateModel(
            name='TableUnit',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'table_unit',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manage_menu.OrderDetail')),
                ('comment', models.CharField(max_length=200)),
                ('comment_score', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.IntegerField()),
                ('guest_account', models.ForeignKey(db_column='guest_account', on_delete=django.db.models.deletion.DO_NOTHING, to='manage_menu.Guest')),
            ],
            options={
                'db_table': 'drink_order',
            },
        ),
        migrations.CreateModel(
            name='CustomizedPlus',
            fields=[
                ('mp_number', models.ForeignKey(db_column='mp_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manage_menu.Multipleplus')),
                ('plus_quantity', models.IntegerField()),
                ('customizedplus_price', models.IntegerField()),
                ('customized', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manage_menu.Customized')),
            ],
            options={
                'db_table': 'customized_plus',
                'unique_together': {('mp_number', 'customized')},
            },
        ),
    ]
