# Generated by Django 2.2.10 on 2021-10-09 16:20

from django.db import migrations, models
import django.db.models.deletion
import manage_menu.storage_sort


class Migration(migrations.Migration):

    dependencies = [
        ('manage_menu', '0002_auto_20210827_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='hide',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='manage_menu.Product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='sort',
            name='photo',
            field=models.ImageField(default='', storage=manage_menu.storage_sort.OverwriteStorage_sort(), upload_to=''),
        ),
    ]
